### PR TITLE
add CMS tab with docs counts, external links and QJD summary

### PR DESCRIPTION
**Pull request by andrewandante**
Adds a section to the CMS with a few helpful links and summaries:

image

I'm aware my design skills aren't up to much but I've done my best 👍

### CODE REVIEW

**Comment by chillu** [comment]
Good stuff! Is this targeted at devs or authors? Things like "documentation URL" imply that it's for authors. In which case I can think of a few ways to make it more user friendly:

- Remove or explain the "indexed in database" count. It doesn't really matter unless it's indexed in Elastic right? Or maybe add a warning if those counts differ?
- Add instructions to the README to set up access to this section for authors, or ensure the default permission is `CMS_ACCESS_CMSMain`
- List the documents waiting to be indexed (and their index), more meaningful to authors
- Change "stopped jobs count" to a warning on top of the section, and hide it when none exist

None of this is a blocker for merging this PR, just got me thinking.

**Comment by andrewandante** [comment]
> Good stuff! Is this targeted at devs or authors? Things like "documentation URL" imply that it's for authors. In which case I can think of a few ways to make it more user friendly:

Yep for authors/admins, so they have a sort of "dashboard" for their search implementation.

>     * Remove or explain the "indexed in database" count. It doesn't really matter unless it's indexed in Elastic right? Or maybe add a warning if those counts differ?

The idea here was to highlight if they were different counts, yes - but there a quite a few edge cases (e.g. a Page can be in multiple indexes but will only ever count once)
 
>     * Add instructions to the README to set up access to this section for authors, or ensure the default permission is `CMS_ACCESS_CMSMain`

Agreed, thought of this as soon as I pushed it 😅 


>     * List the documents waiting to be indexed (and their index), more meaningful to authors

By this do you mean "documents that fit the schema for an index but are currently not indexed? Potentially including "stale" documents?

>     * Change "stopped jobs count" to a warning on top of the section, and hide it when none exist

Sure, makes sense.

One of the things raised by the client was to have a "Trigger Reindex" link, so I think I'll look into that too. Maybe as you say these could be future improvements.

**Comment by chillu** [comment]
> By this do you mean "documents that fit the schema for an index but are currently not indexed? Potentially including "stale" documents?

I mean the actual documents queued up in jobs (should be discoverable through job metadata?)

> One of the things raised by the client was to have a "Trigger Reindex" link

Yeah, which makes the section more "user facing", and needs a higher focus on usability and reduction of tech jargon heh. But as I said, great start, not a blocker.

**Comment by andrewandante** [comment]
Adding as it came up during standup today: a link to a userguide, presumably in this repository 😄 

I've been making incremental improvements but a few of them rely on the Subsites stuff (#47) so I'll hold off until that's merged.

**Comment by andrewandante** [comment]
Updated with Subsite-specific things from my branch, will look at tests next week

**Comment by andrewandante** [comment]
Alrighty, added `Readme.md` instructions, updated screenshot, added permissions and such. Ready for re-review.

I'm 100% sure that there's a better way to style this but I'm not getting into it right now 😅

**Comment by andrewandante** [comment]
@unclecheese any chance of a review on this one?

**Review by unclecheese — APPROVED** [review]
LGTM. Nice stuff!

**Pull request merged**
