### PR TITLE
Fix removal of documents from index when they no longer exist in Silverstripe

### LINKED ISSUE #36: ClearIndexJob will only delete documents that match the schema
Not sure if this is really a bug but I thought I'd note it down in case it comes up and bites someone.

While testing, I indexed two documents in my engine via CURL, as per the example in the docs:

```sh
curl -X POST '<redacto>' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer <redacto>' \
  -d '[
        {
          "id": "park_rocky-mountain",
          "title": "Rocky Mountain",
          "description": "Bisected north to south by the Continental Divide, this portion of the Rockies has ecosystems varying from over 150 riparian lakes to montane and subalpine forests to treeless alpine tundra. Wildlife including mule deer, bighorn sheep, black bears, and cougars inhabit its igneous mountains and glacial valleys. Longs Peak, a classic Colorado fourteener, and the scenic Bear Lake are popular destinations, as well as the historic Trail Ridge Road, which reaches an elevation of more than 12,000 feet (3,700 m).",
          "nps_link": "https://www.nps.gov/romo/index.htm",
          "states": [
            "Colorado"
          ],
          "visitors": 4517585,
          "world_heritage_site": false,
          "location": "40.4,-105.58",
          "acres": 265795.2,
          "square_km": 1075.6,
          "date_established": "1915-01-26T06:00:00Z"
        },
        {
          "id": "park_saguaro",
          "title": "Saguaro",
          "description": "Split into the separate Rincon Mountain and Tucson Mountain districts, this park is evidence that the dry Sonoran Desert is still home to a great variety of life spanning six biotic communities. Beyond the namesake giant saguaro cacti, there are barrel cacti, chollas, and prickly pears, as well as lesser long-nosed bats, spotted owls, and javelinas.",
          "nps_link": "https://www.nps.gov/sagu/index.htm",
          "states": [
            "Arizona"
          ],
          "visitors": 820426,
          "world_heritage_site": false,
          "location": "32.25,-110.5",
          "acres": 91715.72,
          "square_km": 371.2,
          "date_established": "1994-10-14T05:00:00Z"
        }
      ]'
```

Which worked fine and dandy. However, when I ran the `ClearIndexJob`, it found no documents with the `->listDocuments()` call, so didn't remove them, but found 2 with `->getDocumentTotal()`, causing the Job to crash.

Given a case where a developer changes a schema and wants to start fresh, we probably need something like a "force" flag on the Job that just brazenly deletes everything from the index.

### PR DESCRIPTION
**Pull request by madmatt**
Fixes #36.

API changes:
- Add new BatchDocumentRemovalInterface interface and removeAllDocuments method
- Implement removeAllDocuments for AppSearchService, ServiceFake, and NaiveSearchService

Fixes:
- Fix ClearIndexJob so that it runs in a single job run (provided it can finish within limits), and retries up to 5 times
- Add messaging to ClearIndexJob so we know whether it succeeded or not

Tests:
- Add removeAllDocuments to ServiceFake
- Add new and fix existing ClearIndexJob tests

### CODE REVIEW

**Comment by madmatt** [comment]
I can't seem to see codecov stats at all - the links in this PR just go straight to the CodeCov homepage, and logging in doesn't show me anything under the `silverstripe` namespace. I presume this is because the new `removeAllDocuments` method isn't covered but can anyone else access CodeCov to confirm if there's anything else missing tests now?

**Review by unclecheese — APPROVED** [review]
Looks good. My preference would be to create a new interface for BulkDocumentRemover and then check for the implementation of that interface rather than creating a leaky abstraction in DataobjectBatchDocumentProcessor. 

If this is super urgent, we can just merge and mark as technical debt.

**Comment by madmatt** [comment]
No that's fair, I'll jump on that tonight. Thanks @unclecheese!

**Comment by madmatt** [comment]
I'll fix up the test failure tomorrow - I know what is causing it, just need to remember my PHPUnit mocking-fu

**Comment by madmatt** [comment]
Alright I've fixed this up now @unclecheese, hopefully this is what you were after :-)

**Comment by unclecheese** [comment]
Almost there. Just removed the duck typing, and we should be good to go if that passes.

**Comment by madmatt** [comment]
Nice, thanks @unclecheese!

**Pull request merged**
