### PR TITLE
Add configuration for splitting indexes by Subsite

### PR DESCRIPTION
**Pull request by andrewandante**
This relates to #46 

Been experimenting today with how this would work in practice - this setup has given me the result I expect.

Config I was using is (trimmed):

```yaml
SilverStripe\SearchService\Service\IndexConfiguration:
  indexes:
    content-subsite0:
      subsite_id: 0
      includeClasses:
        Page: &page_defaults
          fields:
            title: true
            content: true
            summary: true
        DMS\Model\Document: &document_defaults
          fields:
            title:
              property: Title
            summary:
              property: Summary
    content-subsite4:
      subsite_id: 4
      includeClasses:
        Page:
          <<: *page_defaults
        DMS\Model\Document:
          <<: *document_defaults

```

Happy to have further the discussion, be picked apart or whatever, just thought I'd get my working out in front of some eyes.

### CODE REVIEW

**Comment by chillu** [comment]
Great stuff! Returning `false` from `DataObjectDocument->shouldIndex()` when the subsite doesn't match seems kind of backwards, but I also can't think of a better way to do this with the `DocumentFetcher` structure. Looking at `ReindexJob`, it loops through *every* document of a specific type. We could allow fetchers which "group" those documents by subsite and then set `SubsiteID` state on the job executing the index, but that's getting quite complicated. If you want per-subsite reindexing, I'd rather make this explicit via a `ReindexJob->onlyIndexes` property (in addition to the existing `ReindexJob->onlyClasses`)

**Comment by andrewandante** [comment]
> `ReindexJob->onlyIndexes` property

That makes a lot of sense. Could definitely add it as part of this PR should it be the way forward.

**Comment by unclecheese** [comment]
Looks pretty good to me. Is there a way we could do this with an extension rather than with a new class? Would a `->extend('updateIndexesForDocument', $data)` suffice?

**Comment by andrewandante** [comment]
> Would a `->extend('updateIndexesForDocument', $data)` suffice?

Most likely - would mean looping through again I think but that's much more extensible. Would you keep  the subsites extension in this module, or move it out to a separate one? Perhaps even leave it as an example piece of code?

**Comment by unclecheese** [comment]
You would add another loop, that's correct. But the iterations of that loop would be capped at the number of indexes, which seems like it will stay pretty small?

Having another look, there's room for caching in that method call, anyway, which we should probably be doing. The method is called per _document_ but the only dependency is the _class name_. We could memoise that if we really wanted to. Probably should. 🤷‍♂️

I'm into the idea of an extension just for a clearer separation of concerns, and better maintainability. Being at the mercy of a parent class risks getting more siloed, domain-specific code over time.

**Comment by andrewandante** [comment]
Makes a lot of sense to me. Will test this more thoroughly tomorrow, including caching

**Comment by andrewandante** [comment]
Tested today and works as expected 👍 I suppose tests are probably in order?

**Comment by andrewandante** [comment]
Hmm sorry I'm getting my branches all muddled while I'm working on this project - will push this back to draft and re-open once I've recalibrated

**Comment by madmatt** [comment]
Hey @andrewandante how are you getting on with this one? Will you have time in the near future do you think to resolve the conflicts and re-add?

Thanks!

**Comment by andrewandante** [comment]
Planning to jump back into MBIE search next week so will prioritise fixing this up and opening other PRs for the other bits of functionality in my `mbie_search` branch.

**Comment by andrewandante** [comment]
Alright I think this is "tidy" now 😄

**Review by unclecheese — APPROVED** [review]

**Comment by unclecheese** [comment]
Looks good. I think the extension approach is much better suited.

**Pull request merged**
